import { z } from "zod";
import type { TextContent } from "@modelcontextprotocol/sdk/types.js";
import { parseLookback } from "../utils/toolHelpers";

export const findTraceTool = {
  name: "find_trace",
  description: "given parameters, return traces with specified structure",
  inputSchema: {
    service_name: z
      .string()
      .optional()
      .describe("service_name filters spans generated by a specific service."),
    operation_name: z
      .string()
      .optional()
      .describe(
        "operation_name filters spans by a specific operation / span name.",
      ),
    lookback: z
      .string()
      .optional()
      .default("1h")
      .describe('Time range such as "1h", "30m", "2d"'),
    max_traces: z // differs from API "search_depth" for clarity. Defaults to 1, but can return up to 5.
      .number()
      .int()
      .min(1)
      .max(5)
      .optional()
      .describe(
        "Maximum number of traces to return (approximate). Defaults to 20. Higher values may result in slower responses and more data to analyze.",
      ),
  },
  outputSchema: { result: z.any() },
  handler: async (params: {
    service_name?: string;
    operation_name?: string;
    lookback?: string;
    max_traces?: number;
  }) => {
    const jaegerUrl = process.env.URL;

    if (!jaegerUrl) {
      throw new Error("No URL environmental variable defined!");
    }

    // calculate time ranges
    const endTime = new Date();
    // getTime will convert Date to ms
    const startTime = new Date(
      endTime.getTime() - parseLookback(params.lookback || "1h"),
    );

    const searchDepth = params.max_traces || 1;

    const queryParams = new URLSearchParams({
      "query.start_time_min": startTime.toISOString(), // Jaeger expects ISO 8601 format so this will convert to that
      "query.start_time_max": endTime.toISOString(), // e.g. 2025-01-15T10:00:00.000Z"
      "query.search_depth": searchDepth.toString(),
    });

    if (params.service_name) {
      queryParams.append("query.service_name", params.service_name);
    }
    if (params.operation_name) {
      queryParams.append("query.operation_name", params.operation_name);
    }

    // Build traces URL with query params
    const tracesUrl = `${jaegerUrl}/api/v3/traces?${queryParams.toString()}`;

    console.log(`Fetching sample trace from: ${tracesUrl}`);

    // Fetch raw data from Jaeger
    const response = await fetch(tracesUrl);
    const data = await response.json();

    // Log in docker
    console.log("=== Traces ===");
    console.log(JSON.stringify(data, null, 2));
    console.log("=======================");

    // TextContent is specified in the SDK docs to take a string literal 'text' for type and then just string for the text
    const textContent: TextContent = {
      type: "text",
      text: JSON.stringify(data, null, 2),
    };

    return {
      content: [textContent],
      structuredContent: { result: data },
    };
  },
};
