import { z } from "zod";
import type { TextContent } from "@modelcontextprotocol/sdk/types.js";

export const getTraceSampleTool = {
  name: "find_traces",
  description: "given parameters, return traces with specified structure",
  inputSchema: {
    service_name: z
      .string()
      .optional()
      .describe("service_name filters spans generated by a specific service."),
    operation_name: z
      .string()
      .optional()
      .describe(
        "operation_name filters spans by a specific operation / span name.",
      ),
    start_time_min: z
      .string()
      .optional()
      .describe(
        "start_time_min is the start of the time interval (inclusive) for the query. RFC-3339ns format (e.g., '2025-11-13T10:30:00Z'). If user says '30 minutes ago', convert to absolute timestamp. This field is required.",
      ),
    start_time_max: z
      .string()
      .optional()
      .describe(
        "start_time_max is the end of the time interval (exclusive) for the query. RFC-3339ns format (e.g., '2025-11-13T10:30:00Z'). If user says '30 minutes ago', this time is now. This field is required.",
      ),
    max_traces: z // differs from API "search_depth" for clarity
      .number()
      .int()
      .min(1)
      .max(200) // Maybe increase, 1000 or so, later?
      .optional()
      .describe(
        "Maximum number of traces to return (approximate). Defaults to 20. Higher values may result in slower responses and more data to analyze.",
      ),
  },
  outputSchema: { result: z.any() },
  handler: async (params: { service?: string; lookback?: string }) => {
    const jaegerUrl = process.env.URL;

    if (!jaegerUrl) {
      throw new Error("No URL environmental variable defined!");
    }

    

    // Build traces URL
    const tracesUrl = `${jaegerUrl}/api/v3/traces?query.service_name=${serviceName}&query.start_time_min=${startTimeMin}&query.start_time_max=${startTimeMax}`;

    console.log(`Fetching sample trace from: ${tracesUrl}`);

    // Fetch raw data from Jaeger
    const response = await fetch(tracesUrl);
    const data = await response.json();

    // Log in docker
    console.log("=== Traces ===");
    console.log(JSON.stringify(data, null, 2));
    console.log("=======================");

    // TextContent is specified in the SDK docs to take a string literal 'text' for type and then just string for the text
    const textContent: TextContent = {
      type: "text",
      text: JSON.stringify(data, null, 2),
    };

    return {
      content: [textContent],
      structuredContent: { result: data },
    };
  },
};
